In [3]:
import pandas as pd
folder_name="Latest_ETM_Data"
date=input("Enter the date: ")
ticket_df=pd.read_csv(f'ETM_Data/Ticket-Data-2024-07-{date}.csv')
ticket_df['source'] = ticket_df['source'].replace('Zero Value Ticket', None).fillna(method='ffill').fillna(method='bfill')
ticket_df

Enter the date: 01

,id,depot_code,depot,fleet_no,route_service_type,trip_no,ticket_no,date,time,ticket_type,...,conductor_no,waybill_no,schedule_no,payment_type,direction,Trip_Origin,Trip_Destination,total_ticket_amount,KM,duty_date
0,1,KU,Kundrathur Depot,J1832,Deluxe,1,1,01-07-2024,04:17:46,Adult Ticket,...,C58127,T1719774306123563144,S-88K-A-AS,CASH,88K KUD - DOWN,KUNDRATHUR DEPOT,BROADWAY,13.0,30.0,2024-07-01
1,2,KU,Kundrathur Depot,J1832,Deluxe,1,2,01-07-2024,04:21:48,Adult Ticket,...,C58127,T1719774306123563144,S-88K-A-AS,CASH,88K KUD - DOWN,KUNDRATHUR DEPOT,BROADWAY,17.0,30.0,2024-07-01
2,3,KU,Kundrathur Depot,J1832,Deluxe,1,3,01-07-2024,04:22:18,Adult Ticket,...,C58127,T1719774306123563144,S-88K-A-AS,CASH,88K KUD - DOWN,KUNDRATHUR DEPOT,BROADWAY,27.0,30.0,2024-07-01
3,4,KU,Kundrathur Depot,J1832,Deluxe,1,4,01-07-2024,04:22:37,Adult Ticket,...,C58127,T1719774306123563144,S-88K-A-AS,CASH,88K KUD - DOWN,KUNDRATHUR DEPOT,BROADWAY,33.0,30.0,2024-07-01
4,5,KU,Kundrathur Depot,J1832,Deluxe,1,5,01-07-2024,04:22:51,Adult Ticket,...,C58127,T1719774306123563144,S-88K-A-AS,CASH,88K KUD - DOWN,KUNDRATHUR DEPOT,BROADWAY,17.0,30.0,2024-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978348,1978349,SP,Saidapet Depot,J0924,Deluxe,10,339,02-07-2024,05:14:58,Adult Ticket,...,C56986,T1719832304164824402,S-51-J-AP,CASH,51 - DOWN,TAMBARAM WEST,SAIDAPET,15.0,26.0,2024-07-01
1978349,1978350,SP,Saidapet Depot,J0924,Deluxe,10,340,02-07-2024,05:15:06,Senior Citizen Ticket,...,C56986,T1719832304164824402,S-51-J-AP,FREE,51 - DOWN,TAMBARAM WEST,SAIDAPET,0.0,26.0,2024-07-01
1978350,1978351,SP,Saidapet Depot,J0924,Deluxe,10,341,02-07-2024,05:15:12,Adult Ticket,...,C56986,T1719832304164824402,S-51-J-AP,CASH,51 - DOWN,TAMBARAM WEST,SAIDAPET,15.0,26.0,2024-07-01
1978351,1978352,SP,Saidapet Depot,J0924,Deluxe,10,342,02-07-2024,05:17:52,Adult Ticket,...,C56986,T1719832304164824402,S-51-J-AP,CASH,51 - DOWN,TAMBARAM WEST,SAIDAPET,13.0,26.0,2024-07-01
1978352,1978353,SP,Saidapet Depot,J0924,Deluxe,10,343,02-07-2024,05:23:34,Adult Ticket,...,C56986,T1719832304164824402,S-51-J-AP,CASH,51 - DOWN,TAMBARAM WEST,SAIDAPET,22.0,26.0,2024-07-01

In [4]:
nan_count_A = ticket_df[ticket_df['source'] == 'Zero Value Ticket'].shape[0]
print("Number of rows with Zero Value Ticket in column 'source':", nan_count_A)

Number of rows with 'ZERO VALUE TICKET' in column 'source': 0

In [5]:
ticket_df.to_csv('check_zero.csv')